---
development:
  cloud_name: instapost
  api_key: '121149976254447'
  api_secret: bEE4_l8QoK-fmGUG84eJVVrbV7I
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: instapost
  api_key: '121149976254447'
  api_secret: bEE4_l8QoK-fmGUG84eJVVrbV7I
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: instapost
  api_key: '121149976254447'
  api_secret: bEE4_l8QoK-fmGUG84eJVVrbV7I
  enhance_image_tag: true
  static_image_support: false
