default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: madhav
      password: madhav123
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: instapost_development

test:
  <<: *default
  database: instapost_test

production:
  <<: *default
  database: instapost_production